# Generated by Django 2.2.16 on 2020-10-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riperCars', '0003_fotosgaleria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisiVisi',
            fields=[
                ('ident', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('misi', models.TextField()),
                ('visi', models.TextField()),
            ],
        ),
    ]
