# Generated by Django 2.2.16 on 2020-10-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riperCars', '0004_misivisi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MisiVisi',
            new_name='MisionVision',
        ),
        migrations.RenameField(
            model_name='misionvision',
            old_name='misi',
            new_name='mision',
        ),
        migrations.RenameField(
            model_name='misionvision',
            old_name='visi',
            new_name='vision',
        ),
    ]
